version: "3"
services: 
 db:
  image: mysql
  container_name: docker_db
  ports:
   - "8080:80"
  environment:
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_PASSWORD=password
   - MYSQL_ADD_USER=user
    
    
  